#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ROOT_USER" --dbname postgres <<-EOSQL
    CREATE USER $POSTGRES_APP_USER WITH PASSWORD '$POSTGRES_APP_PASSWORD';
    CREATE DATABASE $POSTGRES_APP_DB OWNER $POSTGRES_APP_USER;
EOSQL